#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time    : 2018/10/21 21:13
# @Author  : Administrator
# @File    : test_00_00_checkskip.py

"""
-----------------------------------------------------
单元测试框架,读取TestCase下面测试用例执行,生成测试报告
-----------------------------------------------------
"""

from Resource.HTMLTestRunner import *
from Resource.sendemail import *
import unittest
import os
import sys
import time


if __name__ == "__main__":

    # 获取测试目录
    path = os.path.abspath(os.path.dirname(sys.argv[0]))
    testcase_path = path + os.sep + "TestCase"

    # 在测试目录寻找测试用例文件
    pattern = "test*.py"
    discover_all_cases = unittest.defaultTestLoader.discover(
        testcase_path, pattern=pattern, top_level_dir=None)

    # 执行用例,将测试结果输出到测试报告中
    now = time.strftime("%Y%m%d%H%M%S", time.localtime())
    with open("Report" + os.sep + now + '_HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(discover_all_cases)

    sendmail(
        "sendmail",
        ["receivemail"],
        "UnitTest Report", "Please check the attach",
        "Report" +
        os.sep +
        now +
        '_HTMLReport.html')

"""需要导入测试用例模块

    from test_mathfunc import TestMathFunc

    # 1.创建实例
    suite = unittest.TestSuite()

    # 2.添加测试用例列表
    # 方法一
    tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_divide")]  # 测试用例

    suite.addTests(tests)  # 将测试用例列表添加到测试组中
    suite.addTest(TestMathFunc("test_multi"))  # 直接用addTest方法添加单个TestCase

    # 方法二
    # 用addTests + TestLoader。不过用TestLoader的方法是无法对case进行排序的
    # loadTestsFromName()，传入'模块名.TestCase名'
    suite.addTests(unittest.TestLoader().loadTestsFromName('test_mathfunc.TestMathFunc'))
    suite.addTests(
        unittest.TestLoader().loadTestsFromNames(['test_mathfunc.TestMathFunc']))  # loadTestsFromNames()，类似，传入列表

    # 方法三
    # loadTestsFromTestCase()，传入TestCase
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    # suite中也可以套suite

    # 3.执行用例,将测试结果输出到测试报告中
    # txt
    # with open('UnittestTextReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    # html
    # with open('HTMLReport.html', 'w') as f:
    #     runner = HTMLTestRunner(stream=f,
    #                             title='MathFunc Test Report',
    #                             description='generated by HTMLTestRunner.',
    #                             verbosity=2
    #                             )
    #     runner.run(suite)

    # 直接将结果输出到控制台
    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)
"""
